### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by benjick** [CollectionFS/Meteor-cfs-graphicsmagick#11]
I've installed GraphicsMagicks for Windows

```Javascript
createThumb = function(fileObj, readStream, writeStream) {
  // Transform the image into a 10x10px thumbnail
  console.log("here");
  console.log(gm.isAvailable);
  gm(readStream, fileObj.name()).resize('100', '100').stream().pipe(writeStream);
};
```

Console says 

```Batch
I20150421-12:44:01.549(2)? here
I20150421-12:44:01.557(2)? true
W20150421-12:44:01.609(2)? (STDERR) events.js:72
W20150421-12:44:01.609(2)? (STDERR)         throw er; // Unhandled 'error' event
W20150421-12:44:01.609(2)? (STDERR)               ^
W20150421-12:44:01.610(2)? (STDERR) Error: write EOF
W20150421-12:44:01.608(2)? (STDERR)
W20150421-12:44:01.610(2)? (STDERR)     at errnoException (net.js:905:11)
W20150421-12:44:01.610(2)? (STDERR)     at Object.afterWrite (net.js:721:19)
=> Exited with code: 8
```

The server then restarts. Anyone tried it with Windows?

**Comment by raix** [comment]
have you added the gm path to the environment var `PATH` on the system?
What SA are you using?

**Comment by benjick** [comment]
Hey

I have `c:\program files\graphicsmagick-1.3.20-q16` in my `PATH` (which contains `gm.exe`)

What does SA mean?

**Comment by raix** [comment]
Sorry, storage adapter, is there a convert.exe

**Comment by benjick** [comment]
I'm using GridFS.

Nope, no `convert.exe`, should that be included?

**Comment by aldeed** [comment]
`gm.isAvailable` is printing `true` so it's probably finding gm ok. Not sure why the error.

**Comment by vikash20186** [comment]
@benjick Did you find any solution? I am facing the same issue

**Comment by benjick** [comment]
Sorry for the late reply. I used
https://github.com/CollectionFS/Meteor-cfs-graphicsmagick to solve it

**Comment by Toki-webdesign** [comment]
Hi,

I have the same problem. gm is undefined. I installed both GraphicsMagicks and Imagemagick. How can I solve it with Meteor-cfs-graphicsmagick?

**Comment by vikash20186** [comment]
Hi,

I updated the path variable and restarted my windows machine. It worked for
me then.

On Wednesday, June 17, 2015, Toki-webdesign <notifications@github.com>
wrote:

> Hi,
>
> I have the same problem. gm is undefined. I installed both GraphicsMagicks
> and Imagemagick. How can I solve it with Meteor-cfs-graphicsmagick?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CollectionFS/Meteor-cfs-graphicsmagick/issues/11#issuecomment-112872749>
> .
>


-- 
Cheers
Vikash Agarwal

+1 732 208 6551
Piscataway, New Jersey, USA.

**Comment by byrne-yan** [comment]
https://github.com/CollectionFS/Meteor-cfs-graphicsmagick  commit  2be9afcdb07c77c0baeed5e575012d7f78874560 solved this issue!

**Comment by BlackICE1979** [comment]
Same problem here, I cannot make it work. I installed GraphicsMagick in Windows and the command gm work at the prompte. Also "npm install gm" and cfs:graphicsmagick were installed with success but I still get the full message "fs:graphicsmagick could not find "graphicsMagic"...". I also get true on the graphicsmagick check on binary path (found). I think it as to do with the npm.require('gm')... I also added the directory to the PATH explicitly and created MAGICK_HOME... No luck. Help please?

**Comment by pedroquinteros1969** [comment]
please help, I have the same error when using cfs-GraphicsMagick, the error is obtained:
W20160905-21:06:09.736(-5)? (STDERR)				
W20160905-21:06:11.059(-5)? (STDERR) events.js:72				
W20160905-21:06:11.060(-5)? (STDERR)         throw er; // Unhandled 'error' event				
W20160905-21:06:11.061(-5)? (STDERR)               ^				
W20160905-21:06:11.062(-5)? (STDERR) Error: write EOF				
W20160905-21:06:11.063(-5)? (STDERR)     at errnoException (net.js:905:11)				
W20160905-21:06:11.064(-5)? (STDERR)     at Object.afterWrite (net.js:721:19)				
 Exited with code: 8				

And the image is stored in mongo zero bytes

Versions:
OS: Winwows 10 Pron N for 64 bits
Meteor: 1.3.4
