### ISSUE TITLE
CentOS deployment error

### ISSUE THREAD

**Issue by ryanbuiltthat** [CollectionFS/Meteor-cfs-graphicsmagick#14]
Trying to deploy my app to a server running CentOs. Seems to be an issue with this package that I can't figure out. Here's the error I'm getting:

	node.js:808
	            throw ee;
	                  ^
	TypeError: Cannot call method 'split' of undefined
	    at Package (packages/cfs:graphicsmagick/gm.js:14:1)
	    at /var/www/vhosts/betabuild.io/planet.betabuild.io/bundle/programs/server/packages/cfs_graphicsmagick.js:110:4
	    at /var/www/vhosts/betabuild.io/planet.betabuild.io/bundle/programs/server/packages/cfs_graphicsmagick.js:119:3
	    at /var/www/vhosts/betabuild.io/planet.betabuild.io/bundle/programs/server/boot.js:222:10
	    at Array.forEach (native)
	    at Function._.each._.forEach (/var/www/vhosts/betabuild.io/planet.betabuild.io/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
	    at /var/www/vhosts/betabuild.io/planet.betabuild.io/bundle/programs/server/boot.js:117:5
	Spawner error:	Application exited by itself with code: 8

I'm running:

`GraphicsMagick 1.3.9 2010-02-04 Q8`
` node v0.10.37`

Here's the collection of cfs packages I'm running (admittedingly I don't need all these just toying around so if there's a conflict I'm fine with removing some).

	cfs:access-point                    0.1.49
	cfs:autoform                        2.2.1
	cfs:filesystem                      0.1.2
	cfs:graphicsmagick                  0.0.18
	cfs:gridfs                          0.0.33
	cfs:s3                              0.1.3
	cfs:standard-packages               0.5.9
	cfs:ui                              0.1.3

**Comment by lemonjp** [comment]
Same problem at Ubuntu 14.04

**Comment by serkandurusoy** [comment]
+1 bump for this. I'm on ubuntu server 14.04 64-bit

```
$ uname -a
$ Linux www.mitolojix.com 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ node -v
$ v0.10.40
```

the following error is thrown:

```
/home/xxxxx/meteor-apps/xxxxx-sandbox-build/bundle/programs/server/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
TypeError: Cannot call method &apos;split&apos; of undefined
    at Package (packages/cfs:graphicsmagick/gm.js:14:1)
    at /home/xxxxx/meteor-apps/xxxxx-sandbox-build/bundle/programs/server/packages/cfs_graphicsmagick.js:110:4
    at /home/xxxxx/meteor-apps/xxxxx-sandbox-build/bundle/programs/server/packages/cfs_graphicsmagick.js:119:3
    at /home/xxxxx/meteor-apps/xxxxx-sandbox-build/bundle/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/home/xxxxx/meteor-apps/xxxxx-sandbox-build/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /home/xxxxx/meteor-apps/xxxxx-sandbox-build/bundle/programs/server/boot.js:117:5
</pre>
```

**Comment by serkandurusoy** [comment]
I can confirm that this works on ubuntu 15.04 but it is a very dark path since it is not an LTS (long term supported) ubuntu version.

**Comment by lemonjp** [comment]
I could not find any solution to develop manually. So I decided to use meteor-up.
It's the best way to develop a meteor app so far. It's really working very well and it's very handy ;-)

**Comment by serkandurusoy** [comment]
Done further testing. This issue *may* be related to permissions that the unix user that runs the node process and process.env namespace may just be lost (undefined) to that user.

If you are using a process manager for node (pm, forever, passenger) this might actually be a creeping issue and you might need to check the documentation of that manager for exposing o/s environment variables.

I'll do more digging and experiments once I find the time.

But in the meantime, I think line 15 could be changed to just initialize process.env.['PATH'] to [] if it is undefined and gm could still be tested on a path that's built internally, making assumptions regarding where the executable may be living. If that also fails, then a log can be sent to the console.

**Comment by ryanbuiltthat** [comment]
I still haven't found a workaround for this which is really complicating things. I'll remove passenger and run through permissions to see if anything can move this along. I hate to think I can't deploy this on a pretty beefy server that runs almost anything because of this package. I can use graphicsmagik from console so i'm lost as to why this only call is getting caught up.

**Comment by serkandurusoy** [comment]
@ryanbuiltthat here's my working config for a meteor app I host on passenger

```
server {
    server_name foo.com;
    root /home/foo/meteor-apps/foo-build/bundle/public;
    passenger_enabled on;
    passenger_sticky_sessions on;
    passenger_env_var PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;
    passenger_env_var MONGO_URL mongodb://localhost:27017/foodb;
    passenger_env_var MONGO_OPLOG_URL mongodb://localhost:27017/local;
    passenger_env_var ROOT_URL http://foo.com;
    passenger_env_var MAIL_URL smtp://noreply%40foo.com:bar@mail.foo.com:587;
    passenger_env_var METEOR_SETTINGS '{ "foo" : "bar" } ';
    passenger_env_var HTTP_FORWARDED_COUNT 1;
    passenger_app_type node;
    passenger_startup_file main.js;
}
```
