### ISSUE TITLE
can you give me why Npm.require not just require (Windows GraphicsMagick do not detection)

### ISSUE THREAD

**Issue by thinksource** [CollectionFS/Meteor-cfs-graphicsmagick#21]
I use windows 10, node 5.5.0 and try to use Meteor 1.2.1
but my ImageMagick do not detected.
I try to do it manually on node script, it works.
```
> allp=process.env['PATH'].split(';')
...
>key=path.join(allp[2],'convert.exe')
'C:\\ImageMagick\\convert.exe'
>fs=require('fs')
...
>fs.existsSync(key)
true
```
You can see I can manually find the convert.exe, but the gm.js can not find the ImageMagick.
I find the different of the require method between my manually do it and your code:
```
fs=Npm.require('fs')
```
I can not find the Npm package in my system, can you explain why using Npm replace of just write reqire('fs'), directly. how to import the Npm object. It seems there is no Npm object in my system.

**Comment by thinksource** [comment]
When I try to use Npm:

```
> fs=Npm.require('fs')
ReferenceError: Npm is not defined
    at repl:1:4
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
```

**Comment by thinksource** [comment]
I think your node is only 0.10.* version. That is the issue
