### ISSUE TITLE
cfs:graphicsmagick could not find "graphicsMagic" or "imageMagic"

### ISSUE THREAD

**Issue by erperejildo** [CollectionFS/Meteor-cfs-graphicsmagick#26]
I'm deploying my Meteor app to my server and I got this error:
![error](https://user-images.githubusercontent.com/5629919/27989959-0790dd3a-643f-11e7-80c4-0ee1fa4bd564.jpg)

I'm using Ubuntu 17.04 and pm2-meteor to deploy

**Comment by Maxosys** [comment]
same issue i am facing on window 10

=> Started proxy.
=> Started MongoDB.
W20170915-18:35:53.534(5.5)? (STDERR) WARNING:
W20170915-18:35:54.208(5.5)? (STDERR) cfs:graphicsmagick could not find "graphicsMagic" or "imageMagic" on the
W20170915-18:35:54.210(5.5)? (STDERR) system.
W20170915-18:35:54.213(5.5)? (STDERR)
W20170915-18:35:54.214(5.5)? (STDERR) I just checked PATH to see if I could find the GraphicsMagick or ImageMagic
W20170915-18:35:54.216(5.5)? (STDERR) unix/mac os/windows binaries on your system, I failed.
W20170915-18:35:54.217(5.5)? (STDERR)
W20170915-18:35:54.218(5.5)? (STDERR) Why:
W20170915-18:35:54.218(5.5)? (STDERR) 1. I may be blind or naive, help making me smarter
W20170915-18:35:54.220(5.5)? (STDERR) 2. You havent added the path to the binaries
W20170915-18:35:54.221(5.5)? (STDERR) 3. You havent actually installed GraphicsMagick or ImageMagick
W20170915-18:35:54.222(5.5)? (STDERR)
W20170915-18:35:54.222(5.5)? (STDERR) *** Make sure "$PATH" environment is configured "PATH:/path/to/binaries" ***
W20170915-18:35:54.223(5.5)? (STDERR)
W20170915-18:35:54.225(5.5)? (STDERR) Installation hints:
W20170915-18:35:54.227(5.5)? (STDERR) * Mac OS X "brew install graphicsmagick" or "brew install imagemagick"
W20170915-18:35:54.228(5.5)? (STDERR) * Linux download rpm or use packagemanager
W20170915-18:35:54.229(5.5)? (STDERR) * Centos "yum install GraphicsMagick"* Windows download the installer and run
I20170915-18:35:54.271(5.5)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
I20170915-18:35:54.297(5.5)? Exception in added observe/observeChanges callback: Error: cfs:graphicsmagick could not find "graphicsMagick" or "imageMagick"
I20170915-18:35:54.299(5.5)?     at gm (packages\cfs_graphicsmagick.js:32:9)
I20170915-18:35:54.300(5.5)?     at Object.createProfilePic (imports/api/Images.js:13:3)
I20170915-18:35:54.302(5.5)?     at packages\cfs_storage-adapter.js:384:29
I20170915-18:35:54.303(5.5)?     at addPassThrough (packages\cfs_storage-adapter.js:450:3)
I20170915-18:35:54.304(5.5)?     at [object Object].FS.Transform.createWriteStream (packages\cfs_storage-adapter.js:381:25)
I20170915-18:35:54.305(5.5)?     at Object.self.adapter.createWriteStream (packages\cfs_storage-adapter.js:200:62)
I20170915-18:35:54.308(5.5)?     at saveCopy (packages\cfs_worker.js:201:37)
I20170915-18:35:54.309(5.5)?     at Object.fsCollection.files.find.observe.added (packages\cfs_worker.js:63:9)
I20170915-18:35:54.311(5.5)?     at _CachingChangeObserver.observeChangesCallbacks.added (packages/minimongo/local_collection.js:1305:28)
I20170915-18:35:54.313(5.5)?     at applyChange.added (packages/minimongo/local_collection.js:707:29)
I20170915-18:35:54.314(5.5)? Exception in added observe/observeChanges callback: Error: cfs:graphicsmagick could not find "graphicsMagick" or "imageMagick"
I20170915-18:35:54.315(5.5)?     at gm (packages\cfs_graphicsmagick.js:32:9)
I20170915-18:35:54.317(5.5)?     at Object.createThumb (imports/api/Images.js:9:3)
I20170915-18:35:54.318(5.5)?     at packages\cfs_storage-adapter.js:384:29
I20170915-18:35:54.319(5.5)?     at addPassThrough (packages\cfs_storage-adapter.js:450:3)
I20170915-18:35:54.320(5.5)?     at [object Object].FS.Transform.createWriteStream (packages\cfs_storage-adapter.js:381:25)
I20170915-18:35:54.320(5.5)?     at Object.self.adapter.createWriteStream (packages\cfs_storage-adapter.js:200:62)
I20170915-18:35:54.321(5.5)?     at saveCopy (packages\cfs_worker.js:201:37)
I20170915-18:35:54.322(5.5)?     at Object.fsCollection.files.find.observe.added (packages\cfs_worker.js:63:9)
I20170915-18:35:54.323(5.5)?     at _CachingChangeObserver.observeChangesCallbacks.added (packages/minimongo/local_collection.js:1305:28)
I20170915-18:35:54.324(5.5)?     at applyChange.added (packages/minimongo/local_collection.js:707:29)
W20170915-18:35:54.325(5.5)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
W20170915-18:35:54.326(5.5)? (STDERR) FS.Transform.createWriteStream transform function failed, Error:
W20170915-18:35:54.328(5.5)? (STDERR) FS.Transform.createWriteStream transform function failed, Error:
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

**Comment by Praxie** [comment]
I got the same exception...

**Comment by dwaynewei** [comment]
I got this issue as well.  have no idea how to deal with it..   looking for help..
